Avoid Bad arguments: value = (nil) error due to indicate_all_messages_as_error (#2556)
The following callstack

amqpvalue_get_list_item_count (value=0x0, size=0x7fffffffda68) at uamqp/src/amqpvalue.c:1345
internal_on_event_send_complete_callback (context=0x55555627dd90, send_result=MESSAGE_SEND_ERROR, delivery_state=0x0)
    at iothub_client/src/iothubtransport_amqp_telemetry_messenger.c:986
indicate_all_messages_as_error (message_sender=0x555555b60860) at uamqp/src/message_sender.c:701
messagesender_close (message_sender=0x555555b60860) at uamqp/src/message_sender.c:846
messagesender_destroy (message_sender=0x555555b60860) at uamqp/src/message_sender.c:795
destroy_event_sender (instance=0x5555556c74f0) at iothub_client/src/iothubtransport_amqp_telemetry_messenger.c:362
telemetry_messenger_stop (messenger_handle=0x5555556c74f0)
    at iothub_client/src/iothubtransport_amqp_telemetry_messenger.c:1666

causes this error message:

Error: Time:Wed Jan 10 20:37:31 2024 File:/home/ewertons/code/s1/azure-iot-sdk-c/uamqp/src/amqpvalue.c Func:amqpvalue_get_list_item_count Line:1345 Bad arguments: value = (nil), size = 0x1ffefff968

Because indicate_all_messages_as_error passes NULL for `delivery_state`.